### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by tap6** [ludoven/OnlyTV-For-TV#1]
<img width="1037" alt="截屏2024-01-06 上午12 45 52" src="https://github.com/ludoven/OnlyTV-For-TV/assets/23492851/97db7324-0e48-416f-a3c0-8d68599b4afa">
大佬，AS的代理也设置了，gradle7.5-bin能下载，但是依旧是构建失败，提示了好几条，有一条是r8什么问题的？搜了很久没找到解决方案才开个issue，望大佬百忙之中抽空看一下，嘿嘿嘿谢谢大佬

**Comment by tap6** [comment]
Make Project/打包apk时没有修改任何内容，但是就是会构建错误，就好奇怪= =

**Comment by advado** [comment]
update Android studio version to "Hedgehog 2023.1.1 at least" then run again. or gradl2 8.2.0 and 8.2 need.
and  update your project changes on git for better future support.

**Comment by tap6** [comment]
牛逼谢谢大佬，问题解决了！把Android Studio升级到"Hedgehog 2023.1.1 at least"之后，再把AGP升级到8.2.1解决了。
<img width="575" alt="截屏2024-01-08 上午10 42 41" src="https://github.com/ludoven/OnlyTV-For-TV/assets/23492851/e8c46954-9579-4298-8f85-b5cbb93c6d66">
<img width="1231" alt="截屏2024-01-08 上午10 42 30" src="https://github.com/ludoven/OnlyTV-For-TV/assets/23492851/3bc08895-1285-4798-b17b-b583a91a2980">
